import type { Product } from '@/types';

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Filtro de Aceite',
    brand: 'Acdelco',
    model: 'Aveo',
    year: 2020,
    line: 'Filtros',
    description: 'Filtro de aceite de alto rendimiento para Chevrolet Aveo.',
    sku: 'AC-FO-001',
    price: 150.00,
    imageUrl: 'https://placehold.co/400x400.png',
  },
  {
    id: '2',
    name: 'Balatas Delanteras',
    brand: 'Brembo',
    model: 'Jetta',
    year: 2022,
    line: 'Frenos',
    description: 'Juego de balatas cerámicas para Volkswagen Jetta.',
    sku: 'BR-FD-002',
    price: 850.50,
    imageUrl: 'https://placehold.co/400x400.png',
  },
  {
    id: '3',
    name: 'Bujía de Iridio',
    brand: 'NGK',
    model: 'Sentra',
    year: 2019,
    line: 'Motor',
    description: 'Bujía de iridio de larga duración para Nissan Sentra.',
    sku: 'NGK-BI-003',
    price: 220.00,
    imageUrl: 'https://placehold.co/400x400.png',
  },
  {
    id: '4',
    name: 'Amortiguador Trasero',
    brand: 'Monroe',
    model: 'Civic',
    year: 2021,
    line: 'Suspensión',
    description: 'Amortiguador de gas para Honda Civic.',
    sku: 'MON-AT-004',
    price: 1200.00,
    imageUrl: 'https://placehold.co/400x400.png',
  },
    {
    id: '5',
    name: 'Batería de Coche',
    brand: 'LTH',
    model: 'Versa',
    year: 2023,
    line: 'Eléctrico',
    description: 'Batería de 12V para Nissan Versa.',
    sku: 'LTH-BC-005',
    price: 2100.75,
    imageUrl: 'https://placehold.co/400x400.png',
  },
  {
    id: '6',
    name: 'Limpiaparabrisas',
    brand: 'Bosch',
    model: 'Tiguan',
    year: 2022,
    line: 'Accesorios',
    description: 'Juego de limpiaparabrisas para VW Tiguan.',
    sku: 'BOS-LP-006',
    price: 450.00,
    imageUrl: 'https://placehold.co/400x400.png',
  },
    {
    id: '7',
    name: 'Filtro de Aire',
    brand: 'Gonher',
    model: 'Mustang',
    year: 2021,
    line: 'Filtros',
    description: 'Filtro de aire de alto flujo para Ford Mustang.',
    sku: 'GON-FA-007',
    price: 350.00,
    imageUrl: 'https://placehold.co/400x400.png',
  },
  {
    id: '8',
    name: 'Radiador',
    brand: 'Valeo',
    model: 'CX-5',
    year: 2018,
    line: 'Enfriamiento',
    description: 'Radiador de aluminio para Mazda CX-5.',
    sku: 'VAL-RD-008',
    price: 3500.00,
    imageUrl: 'https://placehold.co/400x400.png',
  },
];

export const mockBrands = [...new Set(mockProducts.map(p => p.brand))];
export const mockModels = [...new Set(mockProducts.map(p => p.model))];
export const mockYears = [...new Set(mockProducts.map(p => p.year))].sort((a, b) => b - a);
export const mockLines = [
    "Bomba de Agua",
    "Deposito de Anticongelante",
    "Distribucion por Cadena",
    "Fan Clutch",
    "Motoventiladores",
    "Radiadores",
    "Sistema de Accesorios",
    "Sistema de Distribución",
    "Tapones de Depositos y Radiador",
    "Toma de Agua y Termostatos",
    "Tubos de Enfriamiento"
];
